routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\FactoryPipe;
use App\order;
use App\User;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', function () {
    return redirect('/');
});
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('adminCP', 'Admin\PanelController@AdminLogin');

Route::get('/', 'IndexController@index')->name('home');
Route::get('/pipes/{fac}/{pipe}', 'PipeController@index');
Route::get('/showOrder', 'OrderController@store');
Route::get('/user/active/email/{token} ', 'IndexController@activation')->name('activation.account');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

//---user routes---
Route::get('/UserOrder','UserController@userOrder')->middleware('auth');
Route::get('/orders/{id}','UserController@show')->middleware('auth');
//user_edit
Route::get('user/edit/{user}', 'UserController@edit')->name('users.edit');
Route::patch('user/update/{user}','UserController@update')->name('users.update');
//send message
Route::get('user/message', 'UserController@messageForm') ;
Route::post('user/send','UserController@messageSend') ;
//---end user route---

Route::group(['namespace' => 'Admin' , 'middleware' => ['checkAdmin'], 'prefix' => 'admin'],function (){
    Route::get('/panel', 'PanelController@index')->name('panel');
    Route::resource('factoryPipe', 'FactoryPipeController');
    Route::resource('Pipe', 'PipeController');
    Route::post('subPipe','PipeController@subPipe')->name('subPipe');
    Route::get('user', 'PanelController@ManageUsers');
    Route::get('/orders','OrderController@index');
    Route::get('/orders/{id}','OrderController@show');
    Route::get('/user/message','PanelController@message');
    Route::get('/user/deactivate/{id}','UserController@deactivate');
    Route::get('/user/remove/{id}','UserController@remove');
    Route::get('user/edit/{user}', 'UserController@edit')->name('users.edit');
    Route::patch('user/update/{user}','UserController@update')->name('users.update');

});




Route::post('/order/save','UserController@saveOrder');


Route::get('/adminUser',function(){
  User::create([
    'name' =>'mahdi',
    'phone' =>'9351510925',
    'level' =>'admin',
    'email' => 'user@yahoo.com',
    'password' => bcrypt('12345678')
  ]);
  return 'admin created';
});

resources/views/Admin/section/errormassage.blade.php
@if(count($errors)>0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>

@endif

resources/views/Admin/section/footer.blade.php
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/js/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/js/sb-admin-2.js"></script>
<script src="/js/bootstrap-select.js"></script>
<script>
    $('.file_input').change(function() {

        $('#imageName').html(this.files && this.files.length ? this.files[0].name.split('.')[0] : '');

    })
    $('.file_input1').change(function() {

        $('#imageName1').html(this.files && this.files.length ? this.files[0].name.split('.')[0] : '');

    })
</script>
@yield('scripts')
<!-- Page level plugins -->
<!--<script src="vendor/chart.js/Chart.min.js"></script>
-->
<!-- Page level custom scripts -->
<!--<script src="js/demo/chart-area-demo.js"></script>
<script src="js/demo/chart-pie-demo.js"></script>
-->

@yield('script')

{{--
@include('sweet::alert')--}}

resources/views/Admin/section/header.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>


    <!-- Topbar Navbar -->
    <ul class="navbar-nav  ">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                               aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <a class="navbar-brand" href="#"><img src="{{url('/img/logo.png')}}" width="250" alt=""></a>

        <!-- Nav Item - Messages -->


        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">

            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    خروج
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

resources/views/Admin/section/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">

        </div>
        <div class="sidebar-brand-text mx-3">پنل مدیریت</div>
    </a>

    <!-- Divider -->

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{url('admin/panel')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>داشبورد</span></a>
    </li>

    <!-- Nav Item - PipeFactory -->


    <!-- factors -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#invoice" aria-expanded="false" aria-controls="invoice">
            <i class="fas fa-fw fa-cog"></i>
            <span>مدیریت  فاکتورها</span>
        </a>
        <div id="invoice" class="collapse" aria-labelledby="invoice" data-parent="#accordionSidebar" style="">
            <div class="bg-white py-2 collapse-inner rounded">

                <a class="collapse-item" href="{{url('admin/orders')}}">فاکتور ها</a>
            </div>
        </div>
    </li>


    <!-- FactoryPipe -->
    <li class="nav-item">
        <a class="nav-link " href="{{route('factoryPipe.index')}}"   >
            <i class="fas fa-fw fa-cog"></i>
            <span>مدیریت  کارخانه ها</span>
        </a>
     </li>

    <!-- Factory Pipe -->
    <li class="nav-item">
        <a class="nav-link  " href="{{route('Pipe.index')}}"    >
            <i class="fas fa-fw fa-cog"></i>
            <span>مدیریت کالا</span>
        </a>
    </li>


    <!-- Manage Users -->
    <li class="nav-item  ">
        <a class="nav-link" href="{{url('admin/user')}}">
            <i class="fas fa-fw fa-user"></i>
            <span>مدیریت کاربران</span>
        </a>
    </li>

    <li class="nav-item  ">
        <a class="nav-link" href="{{url('admin/user/message')}}">
            <i class="far fa-envelope ml-1"></i>
            <span>نظرات کاربران</span></a>
    </li>

    <li class="nav-item  ">
        <a style="float: right; text-align: right;margin-top: 10px;font-size: 15px;margin-right: 16px;" class="btn btn-danger" href="{{url('logout')}}">
            <i class="fas fa-fw fa-sign-out-alt"></i>
            <span>خروج</span></a>
    </li>

    <!-- Nav Item - Tables -->


    <!-- Divider -->

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->