routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\FactoryPipe;
use App\order;
use App\User;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', function () {
    return redirect('/');
});
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('adminCP', 'Admin\PanelController@AdminLogin');

Route::get('/', 'IndexController@index')->name('home');
Route::get('/pipes/{fac}/{pipe}', 'PipeController@index');
Route::get('/showOrder', 'OrderController@store');
Route::get('/user/active/email/{token} ', 'IndexController@activation')->name('activation.account');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

//---user routes---
Route::get('/UserOrder','UserController@userOrder')->middleware('auth');
Route::get('/orders/{id}','UserController@show')->middleware('auth');
//user_edit
Route::get('user/edit/{user}', 'UserController@edit')->name('users.edit');
Route::patch('user/update/{user}','UserController@update')->name('users.update');
//send message
Route::get('user/message', 'UserController@messageForm') ;
Route::post('user/send','UserController@messageSend') ;
//---end user route---

Route::group(['namespace' => 'Admin' , 'middleware' => ['checkAdmin'], 'prefix' => 'admin'],function (){
    Route::get('/panel', 'PanelController@index')->name('panel');
    Route::resource('factoryPipe', 'FactoryPipeController');
    Route::resource('Pipe', 'PipeController');
    Route::post('subPipe','PipeController@subPipe')->name('subPipe');
    Route::get('user', 'PanelController@ManageUsers');
    Route::get('/orders','OrderController@index');
    Route::get('/orders/{id}','OrderController@show');
    Route::get('/user/message','PanelController@message');
    Route::get('/user/deactivate/{id}','UserController@deactivate');
    Route::get('/user/remove/{id}','UserController@remove');
    Route::get('user/edit/{user}', 'UserController@edit')->name('users.edit');
    Route::patch('user/update/{user}','UserController@update')->name('users.update');

});




Route::post('/order/save','UserController@saveOrder');


Route::get('/adminUser',function(){
  User::create([
    'name' =>'mahdi',
    'phone' =>'9351510925',
    'level' =>'admin',
    'email' => 'user@yahoo.com',
    'password' => bcrypt('12345678')
  ]);
  return 'admin created';
});

app/Pipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pipe extends Model
{
     protected $fillable=['name','price','count','img','mainPipe','unit','parentPipe','property'];

    public function factoryPipe()
    {
        return $this->belongsToMany(FactoryPipe::class,'factorypip_pipe','pipe_id','factorypip_id');
    }


}

app/Http/Controllers/Admin/PipeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\FactoryPipe;
use App\Http\Controllers\Controller;
use App\Http\Requests\PipeRequest;
use App\Http\Requests\subProductRequest;
use App\Pipe;
use Illuminate\Http\Request;
use Session;

class PipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Pipe=Pipe::with('factoryPipe')->get()->toArray();
        return view('Admin.Pipes.all' , compact('Pipe'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $factoryPipe=FactoryPipe::all()->pluck('name','id');
        $MainPipe = Pipe::where('mainPipe','1')->get()->pluck('name','id');
        return view('Admin.Pipes.create',compact('factoryPipe','MainPipe'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store( subProductRequest $request)
    {

         if($request->hasfile('img'))
        {
            $file = $request->file('img');

            $extension = $file->getClientOriginalExtension(); // getting image extension
            $filename =time().'.'.$extension;

            $file->move('uploads/logos/', $filename);
        }



     $Pipe = Pipe::create([
            'name'=>$request->name,
            'img'=> $filename,
            'mainPipe'=>'1',
         ]);

         if ($request->has('factory')){
            $pipe=\App\Pipe::find($Pipe->id);
            $pipe->factoryPipe()->attach($request->factory);
         }
        Session::flash('success', 'محصول سر دسته با موفقیت ثبت شد');

        return redirect()->back();
    }

    public function subPipe(PipeRequest $request)
    {
        if($request->hasfile('img'))
        {
            $file = $request->file('img');

            $extension = $file->getClientOriginalExtension(); // getting image extension
            $filename =time().'.'.$extension;

            $file->move('uploads/logos/', $filename);
        }
        $Pipe = Pipe::create([
            'name'=>$request->name,
            'img'=> $filename,
            'price'=>$request->price,
            'count'=>$request->count,
            'unit'=>$request->unit,
            'parentPipe'=>$request->parentPipe,
            'mainPipe'=>$request->mainPipe,

        ]);
        if ($request->has('factory')){
            $pipe=Pipe::find($Pipe->id);
            $pipe->factoryPipe()->attach($request->factory);
        }
        Session::flash('success', 'اطلاعات کالا با موفقیت ویرایش شد');

        return redirect()->back();
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Pipe $Pipe
     * @return \Illuminate\Http\Response
     */
    public function edit(Pipe $Pipe)
    {

        $factoryPipe=FactoryPipe::all()->pluck('name','id');
        return view('Admin.Pipes.edit',compact('factoryPipe','Pipe'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Pipe $pipe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pipe $Pipe)
    {

        if($request->hasFile('logo_factory')){
            $file = $request->file('logo_factory');
            $extension = $file->getClientOriginalExtension(); // getting image extension
            $filename =time().'.'.$extension;
            if ($file->move('uploads/logos/', $filename)) {
                $Pipe->img = $filename;
            }
        }

        $Pipe->update($request->all());

        if ($request->has('factory')){
            $AsyncPipe=\App\Pipe::find($request->pipeId);
            $AsyncPipe->factoryPipe()->sync($request->factory);
        }
        Session::flash('success', 'اطلاعات دسته بندی با موفقیت ویرایش شد');

        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Pipe $pipe
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Pipe::where('id',$id)->delete();
        return redirect(route('Pipe.index'));
    }
}

app/Http/Controllers/PipeController.php
<?php

namespace App\Http\Controllers;

use App\FactoryPipe;
use App\Pipe;
use Illuminate\Http\Request;

class PipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Pipe $pipe
     * @return \Illuminate\Http\Response
     */
    public function index($fac,$pipe)
    {

        $factory= FactoryPipe::find($fac);
        $Pipes = Pipe::where('parentPipe',$pipe)->get();

          return  view('singleProduct',compact("Pipes",'factory'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pipe  $pipe
     * @return \Illuminate\Http\Response
     */
    public function show(Pipe $pipe)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pipe  $pipe
     * @return \Illuminate\Http\Response
     */
    public function edit(Pipe $pipe)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pipe  $pipe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pipe $pipe)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pipe  $pipe
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pipe $pipe)
    {
        //
    }
}

resources/views/Admin/Pipes/all.blade.php
@extends('Admin.master')
@section('content')
    <div class="container-fluid">


        <div class="page-header ">
            <h2>مدیریت کالا ها</h2>
            <a href="{{route('Pipe.create')}}" class="btn btn-primary btn-sm mb-3">افزودن کالا</a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th class="text-center">نام کالا</th>
                    <th class="text-center"> عکس کالا</th>
                    <th class="text-center"> کارخانه های مرتبط به کالا</th>
                    <th class="text-center">تنظیمات</th>
                </tr>
                </thead>
                <tbody>


                @foreach($Pipe as $item)

                    <tr>
                        <td>  {{$item['name']}} </td>
                        <td style="width: 359px;text-align: center;"> <img style="width:25%" src="{{url('uploads/logos/'.$item['img']) }}"> </td>
                        <td>@foreach($item['factory_pipe'] as $factoryName) {{$factoryName['name']}} @endforeach</td>

                        <td>

                            <a onclick="del_row('<?= $item['id'] ?>','<?= url('admin/Pipe') ?>','<?= Session::token() ?>')"
                               class="btn btn-danger btn-circle pointer-hover  "><i class="fas fa-trash"></i></a>


                            <a class="btn btn-info btn-circle "
                               href="{{ url('admin/Pipe').'/'.$item['id'].'/edit' }}"><i class="fa fa-edit"></i>
                            </a>
                        </td>
                    </tr>

                @endforeach

                </tbody>
            </table>
        </div>


    </div>



@endsection

resources/views/Admin/Pipes/create.blade.php
@extends('Admin.master')
@section('content')
    <h1 class="page-header">
        ثبت کالا
    </h1>
    @if(Session::has('success'))
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
    @endif
    @if(count($errors))

        <div class="alert alert-warning" role="alert">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <nav>
        <div class="nav my-3 mr-3 " id="nav-tab" role="tablist">
            <a class=" btn btn-outline-primary ml-5  active" id="nav-home-tab" data-toggle="tab" href="#nav-sub-product" role="tab"
               aria-controls="nav-sub-product" aria-selected="true">ثبت محصول زیر دسته</a>
            <a class=" btn btn-outline-primary" id="nav-profile-tab" data-toggle="tab" href="#nav-product" role="tab"
               aria-controls="nav-product" aria-selected="false">ثبت محصول سر دسته</a>
        </div>
    </nav>
    <div class="tab-content col-md-6" id="nav-tabContent">
        <div style="margin-bottom: 25px; padding: 10px; background: white; box-shadow: 1px 1px 20px #cccccc54;" class="tab-pane fade show active" id="nav-sub-product" role="tabpanel" aria-labelledby="nav-home-tab">
            <form class="mt-1" action="{{ route('subPipe')}}"  method="post" enctype="multipart/form-data">
                {!! csrf_field() !!}
                <div class="form-group">
                    <label for="title">نام کالا</label>
                    <input type="text" name="name" class="form-control" id="title"
                           placeholder="لطفا نام کالا را وارد کنید">
                </div>
                <div class="form-group">
                    <label for="count">نوع و اینچ کالا</label>
                    <input type="text" name="count" class="form-control" id="count">
                </div>
                <div class="form-group">
                    <label for="price">قیمت</label>
                    <input type="text" name="price" class="form-control" id="price"
                           placeholder="لطفا قیمت  کالا را وارد کنید">
                </div>

                <div class="form-group">
                    <label for="unit">واحد</label>
                    <input type="text" name="unit" class="form-control" id="unit" placeholder="واحد کالا انتخاب کنید">
                </div>

                {{--<div class="form-group">
                    <label>افزودن ویژگی های کالا</label>
                    <input type="text" name="tag_list" id="tag_list" class="form-control">
                    <div class="btn btn-outline-primary add_product_tag" onclick="add_tag()">افزودن</div>
                    <input type="hidden" name="keywords" id="keywords">
                </div>
                <div id="tag_box"></div>--}}


                <div class="form-group">
                    <div class="col-sm 6 pr-0">

                             <span style="cursor: pointer" class="file-input btn btn-primary btn-file mt-4">
                               <i class="fas fa-upload"></i>    انتخاب  عکس کالا  <input class="file_input" name="img"
                                                                                         type="file">

                             </span>
                        <span style="display:inline-block;position:relative;top:15px" id="imageName"></span>
                    </div>
                    <br>
                </div>






                <div class="form-group">
                    <label for="category">انتخاب کالا سر دسته</label>
                    <select name="parentPipe" class="form-control text-right" id="MainPipe"
                            title=" کالا سردسته  را انتخاب کنید...">
                        @foreach( $MainPipe as $id => $name )
                            <option value="{{ $id }}">{{ $name }}</option>
                        @endforeach
                    </select>
                </div>


                <button type="submit" class="btn btn-primary">ثبت کالا</button>
            </form>
        </div>
        <div style=" margin-bottom: 24px; padding: 10px; background: white; box-shadow: 1px 1px 20px #cccccc54;" class="tab-pane fade" id="nav-product" role="tabpanel" aria-labelledby="nav-profile-tab">
            <form class="mt-1" action="{{ route('Pipe.store')}}"  method="post" enctype="multipart/form-data">
                {!! csrf_field() !!}
                <div class="form-group">
                    <label for="title">نام کالا</label>
                    <input type="text" name="name" class="form-control" id="title"
                           placeholder="لطفا نام کالا را وارد کنید">
                </div>




                <div class="form-group  ">
                    <label for="category">انتخاب کارخانه</label>
                    <select name="factory[]" class="form-control text-right" id="factory"
                            title=" کارخانه های مورد نظر خود را انتخاب کنید..." multiple>
                        @foreach( $factoryPipe as $id => $name )
                            <option value="{{ $id }}">{{ $name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <div class="col-sm 6 pr-0">

                             <span style="cursor: pointer" class="file-input btn btn-primary btn-file mt-4">
                               <i class="fas fa-upload"></i>    انتخاب  عکس کالا  <input class="file_input1" name="img"
                                                                                         type="file">

                             </span>
                        <span style="display:inline-block;position:relative;top:15px" id="imageName1"></span>
                    </div>
                    <br>
                </div>

                <button type="submit" class="btn btn-primary">ثبت کالا</button>
            </form>
        </div>

    </div>






@endsection

@section('styles')
    <link href="/css/bootstrap-select.min.css" rel="stylesheet">
@endsection

@section('scripts')
    <script src="/js/bootstrap-select.js"></script>
    <script>
        $('#MainPipe').selectpicker();

        $('#factory').selectpicker();

        //check checkbox checked


        // property

        add_tag = function () {
            var tag_list = document.getElementById('tag_list').value;
            var t = tag_list.split(',');
            var keywords = document.getElementById('keywords').value;
            var string = keywords;
            var count = document.getElementsByClassName('tag_div').length + 1;
            for (var i = 0; i < t.length; i++) {
                if (t[i].trim() != '') {
                    var n = keywords.search(t[i]);
                    if (n == -1) {
                        var r = "'" + t[i] + "'";
                        string = string + "," + t[i];
                        var tag = '<div class="tag_div" id="tag_div_' + count + '">' +
                            '<span class="fas fa-eraser" onclick="remove_tag(' + count + ',' + r + ')"></span>' + t[i];
                        '</div>';
                        $("#tag_box").append(tag);

                        count++;
                    }
                }
            }
            document.getElementById('keywords').value = string;
            document.getElementById('tag_list').value = '';
        };
        remove_tag = function (id, text) {

            $("#tag_div_" + id).hide();
            var keywords = document.getElementById('keywords').value;
            var t = text + ",";
            var t2 = "," + text;
            var a = keywords.replace(t, '');
            var b = a.replace(t2, '');
            document.getElementById('keywords').value = b;
        }

    </script>




@endsection

resources/views/Admin/Pipes/edit.blade.php
@extends('Admin.master')
@section('script')

@endsection
@section('content')

     <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        @if(Session::has('success'))
            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
        @endif
        <div class="page-header mb-4 ">
            <h2> ویرایش   {{$Pipe->name}}</h2>
        </div>
        <form action="{{url('/admin/Pipe').'/'.$Pipe->id }}  " method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            {{method_field('PATCH')}}
            @include('Admin.section.errormassage')
            <div class="form-group col-md-6">
                <label for="title" class="control-label">نام کالا</label>
                <input  type="text" class="form-control" name="title" id="title" placeholder="عنوان را وارد کنید" value="{{$Pipe->name}}" >
            </div>
                <input type="hidden" name="pipeId" value="{{$Pipe->id}}">
            <div class="form-group col-md-6">
                <label for="title">نوع و اینچ کالا</label>
                <input type="text" name="count" value="{{$Pipe->count}}" class="form-control" id="title" >
            </div>
            <div class="form-group col-md-6">
                <label for="title">قیمت</label>
                <input type="text" name="price" class="form-control" id="title" value="{{$Pipe->price}}"  placeholder="لطفا قیمت  کالا را وارد کنید">
            </div>
            <div class="form-group">
                <span style="cursor: pointer" class="file-input btn btn-primary btn-file mt-4 mr-2">
                   <i class="fas fa-upload"></i>    انتخاب عکس لوله  <input id="file_input" name="logo_factory" type="file">
                 </span>

                <span style="display:inline-block;position:relative;top:15px" id="imageName" ></span>


            </div>

            <div class="form-group col-md-6">
                <label for="title">واحد</label>
                <input type="text" name="price" class="form-control" value="{{$Pipe->count}}" id="title" placeholder="واحد کالا انتخاب کنید">
            </div>

            <div class="custom-control custom-checkbox small my-4">
                <input value="1" name="mainPipe" type="checkbox" class="custom-control-input" id="customCheck">
                <label class="custom-control-label" for="customCheck">انتخاب این کالا به عنوان سردسته</label>
            </div>

            <div class="form-group col-md-6 factory">
                <label for="category">انتخاب کارخانه</label>
                <select  name="factory[]" class="form-control text-right " id="factory" title=" کارخانه های مورد نظر خود را انتخاب کنید..." multiple>
                    @foreach( \App\FactoryPipe::all() as $item )

                        <option value="{{$item->id}}" {{ in_array($item->id , $item->pipe()->pluck('id')->toArray()) ? 'selected' : '' }}>{{ $item->name }}</option>
                    @endforeach
                </select>
            </div>


            <div class="form-group">

                <button type="submit" class="btn btn-success btn-block w-25 mt-5">ویرایش</button>
            </div>
        </form>
    </div>

@endsection
@section('styles')
    <link href="/css/bootstrap-select.min.css" rel="stylesheet">
@endsection

@section('scripts')
    <script src="/js/bootstrap-select.js"></script>

    <script>
        $('#factory').selectpicker();
    </script>

    <script>
        document.querySelector("#customCheck").addEventListener('change',function () {

            if (document.querySelector("#customCheck").checked){
                document.querySelector(".factory").style.display="block";

            }else {
                document.querySelector(".factory").style.display="none";
            }
        })
    </script>
@endsection