routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\FactoryPipe;
use App\order;
use App\User;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', function () {
    return redirect('/');
});
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('adminCP', 'Admin\PanelController@AdminLogin');

Route::get('/', 'IndexController@index')->name('home');
Route::get('/pipes/{fac}/{pipe}', 'PipeController@index');
Route::get('/showOrder', 'OrderController@store');
Route::get('/user/active/email/{token} ', 'IndexController@activation')->name('activation.account');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

//---user routes---
Route::get('/UserOrder','UserController@userOrder')->middleware('auth');
Route::get('/orders/{id}','UserController@show')->middleware('auth');
//user_edit
Route::get('user/edit/{user}', 'UserController@edit')->name('users.edit');
Route::patch('user/update/{user}','UserController@update')->name('users.update');
//send message
Route::get('user/message', 'UserController@messageForm') ;
Route::post('user/send','UserController@messageSend') ;
//---end user route---

Route::group(['namespace' => 'Admin' , 'middleware' => ['checkAdmin'], 'prefix' => 'admin'],function (){
    Route::get('/panel', 'PanelController@index')->name('panel');
    Route::resource('factoryPipe', 'FactoryPipeController');
    Route::resource('Pipe', 'PipeController');
    Route::post('subPipe','PipeController@subPipe')->name('subPipe');
    Route::get('user', 'PanelController@ManageUsers');
    Route::get('/orders','OrderController@index');
    Route::get('/orders/{id}','OrderController@show');
    Route::get('/user/message','PanelController@message');
    Route::get('/user/deactivate/{id}','UserController@deactivate');
    Route::get('/user/remove/{id}','UserController@remove');
    Route::get('user/edit/{user}', 'UserController@edit')->name('users.edit');
    Route::patch('user/update/{user}','UserController@update')->name('users.update');

});




Route::post('/order/save','UserController@saveOrder');


Route::get('/adminUser',function(){
  User::create([
    'name' =>'mahdi',
    'phone' =>'9351510925',
    'level' =>'admin',
    'email' => 'user@yahoo.com',
    'password' => bcrypt('12345678')
  ]);
  return 'admin created';
});

resources/views/Admin/PipeFactory/all.blade.php
@extends('Admin.master')
@section('content')
    <div class="container-fluid">


        <div class="page-header ">
            <h2>مدیریت کارخانه ها</h2>
            <a href="{{route('factoryPipe.create')}}" class="btn btn-primary btn-sm mb-3">افزودن کارخانه</a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>نام کار خانه</th>
                    <th>عکس کارخانه</th>
                    <th>تنظیمات</th>
                </tr>
                </thead>
                <tbody>


                @foreach($factoryPipe as $facpipe)
                    <tr>
                        <td><a href="#"> {{$facpipe->name}}</a></td>
                        <td> <img width="50" src="{{url('uploads/logos/'.$facpipe->img) }}"> </td>

                        <td>

                            <a onclick="del_row('<?= $facpipe->id ?>','<?= url('admin/factoryPipe') ?>','<?= Session::token() ?>')"
                               class="btn btn-danger btn-circle pointer-hover  "><i class="fas fa-trash"></i></a>



                            <a class="btn btn-info btn-circle "
                               href="{{ url('admin/factoryPipe').'/'.$facpipe->id.'/edit' }}"><i class="fa fa-edit"></i> </a>


                        </td>
                    </tr>

                @endforeach

                </tbody>
            </table>

        </div>
        <div style="text-align: center">
            {!! $factoryPipe->render() !!}
        </div>

    </div>



@endsection

resources/views/Admin/PipeFactory/create.blade.php
@extends('Admin.master')
@section('script')


@endsection
@section('content')
    <div class="container-fluid">
        @if(Session::has('success'))
            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
        @endif
        <div class="page-header mb-5 ">
            <h2>ایجاد کارخانه</h2>
        </div>
        <form action="{{route('factoryPipe.store')}}  " method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            @include('Admin.section.errormassage')
            <div class="form-group col-md-6">
                <label for="title" class="control-label">نام کارخانه</label>
                <input type="text" class="form-control mt-2" name="factory_name" id="title"
                       placeholder="عنوان را وارد کنید" value="{{old('factory_name')}}">
            </div>

            <div class="form-group">
                <div class="col-sm 6">

                 <span style="cursor: pointer" class="file-input btn btn-primary btn-file mt-4">
                   <i class="fas fa-upload"></i>    انتخاب  لوگو  کارخانه  <input id="file_input" name="logo_factory" type="file">

                 </span>
                    <span style="display:inline-block;position:relative;top:15px" id="imageName" ></span>


                </div>
                <br>
            </div>
            <div class="form-group">

                <button type="submit" class="btn btn-success btn-block w-25 mt-5">ارسال</button>
            </div>
        </form>
    </div>

@endsection

resources/views/Admin/PipeFactory/edit.blade.php
@extends('Admin.master')
@section('script')

@endsection
@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        @if(Session::has('success'))
            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
        @endif
        <div class="page-header mb-4 ">
            <h2>ویرایش کارخانه</h2>
        </div>
        <form action="{{url('/admin/factoryPipe').'/'.$factoryPipe->id }}  " method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            {{method_field('PATCH')}}
            @include('Admin.section.errormassage')
            <div class="form-group col-md-6">
                <label for="title" class="control-label">نام کارخانه</label>
                <input type="text"  class="form-control" name="title" id="title" placeholder="عنوان را وارد کنید" value="{{$factoryPipe->name}}" >
            </div>


            <div class="form-group">
                <img style="width: 15%;" src="{{url('uploads/logos/'.$factoryPipe->img) }}">
            </div>

            <div class="form-group">
                <span style="cursor: pointer" class="file-input btn btn-primary btn-file mt-4 mr-2">
                   <i class="fas fa-upload"></i>    انتخاب  لوگو  کارخانه  <input id="file_input" name="logo_factory" type="file">
                 </span>

                <span style="display:inline-block;position:relative;top:15px" id="imageName" ></span>


            </div>


            <div class="form-group">

                <button type="submit" class="btn btn-success btn-block w-25 mt-5">ارسال</button>
            </div>
        </form>
    </div>

@endsection